### ISSUE TITLE
No /live or /ready registered

### ISSUE THREAD

**Issue by bradennapier** [gquittet/graceful-server#20]
I am using this module and it does not appear to work.

I do not appear to get any registrations for `live` or `ready` -- i registered an onRoute before it and nothing happened either. 

Also would be nice if we could register `closePromises` after the fact.. so if future dependencies could call `fastify.onShuttingDown(async () => {})` to provide their own shutdown requirements within the plugin itself (that is what i implemented myself via the closePromises in example below...)

```ts
/**
   * @see https://github.com/gquittet/graceful-server
   * @see https://github.com/gquittet/graceful-server#integration-with-kubernetes
   * @see https://github.com/gquittet/graceful-server#integration-with-docker (for Docker HealthCheck if needed)
   */
  const graceful = GracefulServer(server.server, {
    kubernetes: true,
    timeout: 5000,
    healthCheck: true,
    livenessEndpoint: '/live',
    readinessEndpoint: '/ready',
    closePromises: [
      async function handleShuttingdown() {
        logger.server.info('Starting Graceful Shutdown');
        await Promise.all(
          Array.from(server.handleOnShuttingDown.entries()).map(
            ([name, fn]) => {
              logger.server.info(`Shutting Down "${name}"`);
              return fn(server);
            },
          ),
        );
        await onShuttingDown?.(server);
      },
    ],
  });

```

**Comment by bradennapier** [comment]
hmm nvm it works not sure what happened with that -- odd

**Comment by gquittet** [comment]
Which Node version are you using ?

At the time, I support only node versions up to Node 18

I will test the library with Node 19 :)

**Comment by gquittet** [comment]
Great idea with shutting down handlers 👍 

You can open a pull request if you want 

I can also implement it as you which 🙂

**Comment by bradennapier** [comment]
We use it node 18 plenty!

**Comment by dub-rp** [comment]
> hmm nvm it works not sure what happened with that -- odd

I just encountered the same exact issue, was working originally with Node v18 but then switched to Node v16.14.2.  The process starts fine but the routes for `/live` and `/health` return 404s, quite odd.

In either case (working or failing) it never registers via the `onRoute` hook.

**Comment by gquittet** [comment]
Thanks adding more information.
I will look at it this evening 👀 

I reopen the issue to work on it

**Comment by gquittet** [comment]
@dub-rp 

> In either case (working or failing) it never registers via the onRoute hook.

It's not registering via the `onRoute` `fastify` hook it's normal.

I'm using the built-in `NodeJS` HTTP library to be framework/library agnostic.

You can check this here:
- https://github.com/gquittet/graceful-server/blob/46858dbd83dc774da22bfa5b2597ad0de967b7c9/src/core/improvedServer.ts#L28
- https://github.com/gquittet/graceful-server/blob/ccbee8eb4d7529c11d8fe51b3042fdfd745fe4df/src/util/onRequest.ts

> /live and /health

The default endpoint without any customization is `/live` and `/ready` 

After investigating, I found this is a compatibility issue with Fastify 4 and node 16 and 14.

I'm checking the fastify source code to find the bug, and I'll make a PR to the fastify official repository.

I will make a patch in Graceful Server during the approval time of my pull request.

For now, you can use Node 18 and Fastify 4 and everything will work 👍 

Or using Node 16 and lower with Fastify 3 

I keep this issue open to keep you in touch.

**Comment by gquittet** [comment]
@bradennapier 

> I do not appear to get any registrations for live or ready -- i registered an onRoute before it and nothing happened either.

Same answer as above, it's not registering via the `onRoute` `fastify` hook it's normal.

I'm using the built-in `NodeJS` HTTP library to be framework/library agnostic.

You can read above the full explanation 🙂 

> I am using this module and it does not appear to work.

What do you expect this module does? 🙂

It only adds two endpoints for readiness and liveness and handle connections (HTTP, datasources, etc)

**Comment by gquittet** [comment]
Here is my simple working example with Node 18 and Fastify 4

It does not work with Node 14/16 and Fastify 4 but it's working with Node 14/16 and Fastify 3

```javascript
const fastify = require("fastify")({ logger: true });
const GracefulServer = require("@gquittet/graceful-server");

fastify.addHook("onRoute", (routeOptions) => {
  console.log("onRoute hook", routeOptions);
});

fastify.get("/", async (request, reply) => {
  return { hello: "world" };
});

const gracefulServer = GracefulServer(fastify.server);

gracefulServer.on(GracefulServer.READY, () => {
  console.log("Server is ready");
});

gracefulServer.on(GracefulServer.SHUTTING_DOWN, () => {
  console.log("Server is shutting down");
});

gracefulServer.on(GracefulServer.SHUTDOWN, (error) => {
  console.log("Server is down because of", error.message);
});

const start = async () => {
  try {
    await fastify.listen({ port: 3000 });
    fastify.log.info(`server listening on ${fastify.server.address().port}`);
    gracefulServer.setReady();
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();
```

**Comment by gquittet** [comment]
I found the commit that breaks the compatibility with Fastify 4 and Node 16/14 👍 

[f0281948cfcb04cd1c5c93a330823278e4a1b44f](https://github.com/fastify/fastify/commit/f0281948cfcb04cd1c5c93a330823278e4a1b44f)

I will debug this commit later and make a pull request on the Fastify project 🙂

**Comment by gquittet** [comment]
A quick workaround to wait until I make the PR is to add `host` key to fastify `listen` options:

```javascript
await fastify.listen({ port: 3000, host: '' });
```

**Comment by gquittet** [comment]
OK I understand the issue,

Fastify by default is listening on IPv4 and IPv6 at the same time using a workaround with 2 servers.

But when you use fastify.server you only get the IPv4 one.

So, Graceful Server is only on the IPv4 server.

When you replace localhost with 127.0.0.1 in your url it's working.

I will make an issue to explain the situation to the fastify team and I will make a pull request.

You can use this workaround pending : https://github.com/gquittet/graceful-server/issues/20#issuecomment-1396263371

**Comment by gquittet** [comment]
I have updated the documentation on my side : https://github.com/gquittet/graceful-server#fastify 🙂

**Comment by dub-rp** [comment]
Great stuff @gquittet - appreciate you looking into this.  I'm just using Node v18 so working around the issue, no impact for me.  Makes sense it doesn't trigger `onRoute` if it's a generic tool - I saw it listed in the https://www.fastify.io/ecosystem/ page so I think I assumed it was integrated with fastify.

**Comment by gquittet** [comment]
I close this issue since it occurs only with Node 14 & 16 and Graceful Server no longer supports Node versions below 17
