### ISSUE TITLE
ESM module import requires using .default property

### ISSUE THREAD

**Issue by StepanMynarik** [gquittet/graceful-server#23]
When you have `"type": "module",` specified in your _package.json_, then using any types from _GracefulServer_ must be postfixed with _default_, like so `GracefulServer.default`.

Import:
`import GracefulServer from "@gquittet/graceful-server";`

Not a blocker, but getting a nicer experience with ESM would be sweet👍 

Reference of a similar issue in unrelated repository: https://github.com/ajv-validator/ajv/issues/1381

**Comment by gquittet** [comment]
Hello @StepanMynarik 👋 

Thank you for your interest in the project.

I will check what I can do to improve the DevX with ESM and Graceful Server 👀

**Comment by gquittet** [comment]
Hello @StepanMynarik 👋 

Just a quick update, I will work on this issue this week 👍 

If you have a simple example of the issue, share it with me 😉 

Have a nice day! 🌻

**Comment by StepanMynarik** [comment]
@gquittet 

Great news!

Super busy with work lately, but I can definitely share here my _tsconfig.json_ and _package.json_ important sections.

### tsconfig.json
```
{
  "extends": "fastify-tsconfig",
  "include": ["src/**/*.ts"],
  "compilerOptions": {
    "composite": true,
    "outDir": "dist",
    "sourceMap": true,
    "target": "ES2018",
    "lib": ["ES2018"],
    "noUncheckedIndexedAccess": true
  }
}```

### package.json
```
{
  "name": "gamdi-api",
  "version": "0.0.1",
  "private": true,
  **"type": "module",**
  "scripts": {
    ...
  },
  "dependencies": {
    ...
    **"@gquittet/graceful-server": "^4.0.8",**
    ...
  },
  "devDependencies": {
    ...
    **"fastify-tsconfig": "^2.0.0",**
    ...
    **"typescript": "~5.3.2"**
  }
}```

**Comment by gquittet** [comment]
Hello @StepanMynarik 👋 

Now Graceful Server is ESM ready! 🎉 

I close the issue

**Comment by StepanMynarik** [comment]
Unfortunately after updating to `5.0.0` the imported `GracefulServer` reports as `any`.

I can click it, go to definition and see the following `declare const GracefulServer: ((server: Server, options?: IGracefulServerOptions) => IGracefulServer) & typeof State;` but VSCode ignores it for some reason and shows as `any`.

**Comment by gquittet** [comment]
Sorry for that, everything is working fine with version `5.0.2`

I just published it 🚀

I switch from `webpack` to `tsup` and it was a pain in the *** for me to set up the types, absolute imports and so on 😅

Have a nice day ☀️

**Comment by StepanMynarik** [comment]
Epic! It works fine now.

Thank you ❤️
