### ISSUE TITLE
How do I shutdown the server programatically?

### ISSUE THREAD

**Issue by cjroebuck** [gquittet/graceful-server#25]
At the end of my tests in CI, I need to close the node server (in my case, im using fastify), I noticed that the shutdown method is only called when a signal such as SIGINT or SIGTERM is received, like it would be when running in kubernetes, but it is difficult to send signals when running in an automated test environment without causing the test framework process to quit too.

In the `afterAll` of my test, I need to get gracefulServer to shutdown, but i cannot get it to run the shutting down / shutdown logic, and so my tests are not exiting correctly.. I've tried calling .close on both the fastify instance and the fastify.server instance (which graceful server wraps), but no dice..

Any ideas what to do here? Can the shutdown method be exposed on the gracefulServer instance?

**Comment by gquittet** [comment]
Hello @cjroebuck 👋

I'm getting into it this weekend 👨‍💻

Have a nice day! ☀️

**Comment by gquittet** [comment]
Hello @cjroebuck 👋 

Now you can use the stop function directly from the gracefulServer instance 👍 

Enjoy! ☀️ 

If you need any help on that, send me a message via this issue.

If you like my work, share my project with people you know or sponsor the project, I'll be really grateful 🤟
