### ISSUE TITLE
CJS issues with Typescript

### ISSUE THREAD

**Issue by ben-hn** [gquittet/graceful-server#29]
I'm trying to `import GracefulServer from '@gquittet/graceful-server';`

and I'm getting `TS7016: Could not find a declaration file for module @gquittet/ graceful-server.`

I think it's something to do with having 

```
    "module": "node16",
    "moduleResolution": "node16"
``` 

in my tsconfig.json

Swapping them for 

```
    "module": "ES2022",
    "moduleResolution": "Bundler",
```

makes it happier.

**Comment by gquittet** [comment]
Hello @ben-hn 👋 

Just to say I fixed the issue in the version 5.2.3 🚀 

Enjoy this new release! 🎉 

I wish you a sunny day 🌻
