### ISSUE TITLE
Empty replies during grace/timeout period

### ISSUE THREAD

**Issue by MichielDeMey** [gquittet/graceful-server#5]
Hi

I'm trying to create a simple implementation example using Fastify and I noticed that once a `SIGTERM` or `SIGINT` signal is sent to the server that only the liveness and healthcheck endpoints continue to respond to requests.

All other routes send an empty reply.

I'm wondering is this is intended behaviour?

I'm currently using GCLB (Google Cloud Load Balancer) with Kubernetes ingress controllers and NEGs.
As far as I'm aware, the GCLB will continue to serve client traffic to all pods until the health check fails.
However, the server will respond with an empty reply which might get propagated back to the client before the health checks fail causing a couple of seconds downtime.

Some more information regarding this:
https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#traffic_does_not_reach_endpoints

Full code for my experiment below. In this case `/foo` will result in an empty reply when stopping the server.

Note that I've set a timeout of 30s. which is the time it should keep responding with a 503 to allow for health checks to fail.
```js
const Fastify = require('fastify')
const GracefulServer = require('@gquittet/graceful-server')

const fastify = Fastify({ logger: true })
const gracefulServer = GracefulServer(fastify.server, {
  timeout: 30000,
  closePromises: [fastify.close]
})

// Health check
fastify.get('/foo', (req, res) => res.send('bar'))

const start = async () => {
  try {
    await fastify.listen(8080)
    gracefulServer.setReady()
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}

start()
```

Any thoughts on this?

**Comment by gquittet** [comment]
Hello @MichielDeMey,

Thank you for reporting this issue.

I'm looking at it right after my work day.

Thank you 🙏

**Comment by gquittet** [comment]
Okay, I get the point.

Once the server crashes, it is no longer in the "ready" state.  
This means that every new incoming request will be destroyed (hence the empty response).

- https://github.com/gquittet/graceful-server/blob/7694570cbfea67c8973f04388bf9e88c9e42fd15/src/core/improvedServer.ts#L39
- https://github.com/gquittet/graceful-server/blob/7694570cbfea67c8973f04388bf9e88c9e42fd15/src/core/improvedServer.ts#L51

The purpose of the timeout is to terminate ongoing requests, as well as to disconnect cleanly from all data sources.

So here during 30 seconds, the server will try to run the shutdown callback and wait ongoing requests to finish. The only working routes during this state are the liveness that send you a 200 and the readiness that send you a 503.

In the shutdown callback you don't necessarily have to turn off the server, the library takes care of that for you.

```javascript
const gracefulServer = GracefulServer(fastify.server, {
  timeout: 30000,
  closePromises: [fastify.close]
})
```

What I can do is to create a new timeout that will give more time for incoming traffic.

The health check endpoints are handled by NodeJS itself (thanks to graceful server).

If you want to change your readiness by /foo, you can do it.

```javascript
const gracefulServer = GracefulServer(fastify.server, {
  readinessEndpoint: '/foo',
  timeout: 30000,
  closePromises: [fastify.close]
})
```

I hope I have been as clear as possible.

**Comment by MichielDeMey** [comment]
Hi Guillaume

Thanks for the clarifications.

I think adding an additional timeout to allow for incoming requests to be handled is a good solution since that is exactly what I need.

It's not that the service is crashing, but it receives a SIGTERM from kubernetes asking to cleanly shutdown the service.
However, when coupled with ingress controllers (especially cloud load balancers) we still need to be able to serve traffic to those pods while simultaneously serving a `5xx` status to the readiness endpoint.

De-registering the pod from the NEG for the load balancer takes some time and we need to be able to serve traffic for that period so we will not end up with client-side errors. 🙂 

There's also some information regarding this behaviour in the Terminus README.
https://github.com/godaddy/terminus#how-to-set-terminus-up-with-kubernetes

**Comment by gquittet** [comment]
Hello @MichielDeMey,

I just released the version 2.4.0 of graceful-server 🚀

You can now set up a period of grace with `gracePeriod` as you can read it in the documentation : https://github.com/gquittet/graceful-server#igracefulserveroptions

```typescript
const gracefulServer = GracefulServer(fastify.server, {
  timeout: 30000,
  gracePeriod: 5
})
```

I just test it and everything is running fine here locally.

Can you retry with your Kube cluster to check if everything is running fine ? 

Thank you ! 🙏

**Comment by gquittet** [comment]
Hello @MichielDeMey 

Without any answer from you, I'll have to close this issue tomorrow.

It's working on my side.

Have a nice day.

**Comment by MichielDeMey** [comment]
Hey @gquittet , sorry for the late reply!

I just updated the dependency and checked again.
It does not look like the implementation is what we need for the graceful timeout to work for cloud ingress controllers.

I've used the following config (same server as before):
```js
const gracefulServer = GracefulServer(fastify.server, {
  timeout: 5000,
  gracePeriod: 10
})
```

I then have 3 simple `curl` commands running in the background to check the API behaviour.
```bash
while sleep 1; do curl http://127.0.0.1:8080/live -vvv; done       # liveness endpoint
while sleep 1; do curl http://127.0.0.1:8080/ready -vvv; done      # readiness probe
while sleep 1; do curl http://127.0.0.1:8080/foo -vvv; done        # example endpoint, returns 200
```

When I send a `SIGTERM` to the server `kill -SIGTERM 1234` (where 1234 is the pid) the following happens for the next 10 seconds:
```
/live: 200
/ready 200
/foo 200
```
After 10 seconds (graceful period), the following is returned for the next 5 seconds (timeout):
```
/live: 200
/ready 503
/foo connection refused
```

---

What should be happening is that the readiness endpoint returns a `503` as soon as the `SIGTERM` is received.
Any other API endpoints should still respond with their original response for the duration of the graceful period.

As soon as the `SIGTERM` is received for the next 10 seconds (graceful period):
```
/live: 200
/ready 503
/foo 200
```

This signals the loadbalancer that the endpoint is no longer ready and should be de-registered from the loadbalancer backend config.

The process of de-registering an endpoint might take some time, depending on the cloud provider and health check settings (interval, unhealthy threshold, etc.) hence the graceful period.

The key here is that all API endpoints (except the readiness route) should still serve traffic as normal when a `SIGTERM` is received and the graceful period is running.

I hope this makes sense. 🙂

**Comment by gquittet** [comment]
Hello @MichielDeMey,

Glad to hear from you.
I hope you are well.

Your explanations are very clear and make sense.

I'm doing this tonight so the fix will be available in the morning 🙂

**Comment by gquittet** [comment]
I just added a Kubernetes mode to let it manages the incoming traffic 🎉  (https://github.com/gquittet/graceful-server/issues/11)

I removed the grace period because it is no longer useful. (https://github.com/gquittet/graceful-server/issues/13)

### How to use it?

Just set the Kubernetes mode to true in the `@gquittet/graceful-server` option.

```js
const gracefulServer = GracefulServer(fastify.server, {
  timeout: 5000,
  kubernetes: true
})
```

All is working as expected on my side 💪 

I reopen this issue for a period of 14 days.

**Comment by MichielDeMey** [comment]
I can confirm that everything now works as intended, thanks @gquittet!
